### PR TITLE
Always read/write files using UTF-8 encoding

### PR DESCRIPTION
**Pull request by jacobstanley**
This is an attempt to fix the farm build issue: https://github.com/ambiata/eminence/pull/183

/cc @tmcgilchrist

### CODE REVIEW

**Comment by olorin** [comment]
:100: for always writing stuff in UTF-8, but why not use `Data.Text.IO.{write,read}File`?

**Comment by jacobstanley** [comment]
@olorin as far as I can tell `{write,read}File` uses whatever the system encoding is (i.e. the `LANG` environment variable)

**Comment by olorin** [comment]
Yep, you're correct, I was misreading the docs. :shaved_ice:

**Comment by tmcgilchrist** [comment]
It's failing for other reasons now, so I suppose that's classified as success.

**Comment by jacobstanley** [comment]
Added a yak for this: https://github.com/ambiata/yak/issues/75

**Pull request merged**
