### PR TITLE
Fix missing-home-modules warning

### PR DESCRIPTION
**Pull request by erikd**
Lets see if this builds with all combinations of GHC and cabal.

### CODE REVIEW

**Comment by justanotherdot** [comment]
:crossed_fingers:

**Comment by justanotherdot** [comment]
Looks like something went awry with `apt`:

```
1.52s$ sudo add-apt-repository -y ppa:hvr/ghc
gpg: keyring `/tmp/tmpqf4cgrob/secring.gpg' created
gpg: keyring `/tmp/tmpqf4cgrob/pubring.gpg' created
gpg: requesting key F6F88286 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpqf4cgrob/trustdb.gpg: trustdb created
gpg: key F6F88286: public key "Launchpad PPA for Herbert V. Riedel" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
before_install.2
22.18s$ sudo apt-get update
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Hit:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release
Ign:9 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:7 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:10 http://dl.google.com/linux/chrome/deb stable Release
Hit:11 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:12 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:13 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:15 https://dl.hhvm.com/ubuntu trusty InRelease
Err:20 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
  Failed to connect to packagecloud.io port 443: Connection timed out
Hit:21 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:22 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Err:8 http://dl.bintray.com/apache/cassandra 39x InRelease
  Unexpected type excepted 21 != 5
Err:23 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:24 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:25 http://ppa.launchpad.net/hvr/ghc/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:26 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:27 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:28 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Hit:29 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Reading package lists... Done
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/hvr/ghc/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
0.63s$ sudo apt-get install hoogle cabal-install-$CABALVER ghc-$GHCVER
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cabal-install-2.0
E: Couldn't find any package by glob 'cabal-install-2.0'
E: Couldn't find any package by regex 'cabal-install-2.0'
E: Unable to locate package ghc-8.2.2
E: Couldn't find any package by glob 'ghc-8.2.2'
E: Couldn't find any package by regex 'ghc-8.2.2'
The command "sudo apt-get install hoogle cabal-install-$CABALVER ghc-$GHCVER" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by erikd** [comment]
This works, but only because the `.travis.yml` file has:
```
 - 'if [ ${CABALVER} = "2.0" ]; then
      cabal sdist ;
    fi`
```
and that's because cabal 1.24 will complain about missing `other-modules` in when it runs `sdist`.

**Comment by erikd** [comment]
@justanotherdot Yeah, the lauchpad PPA is a bit unreliable. When this happens, a restart of the job usually fixes it (as it did this time).

**Review by tmcgilchrist — APPROVED** [review]

**Pull request merged**
