### PR TITLE
Make mafia home Ambiata agnostic.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Is there any harm in making the `MAFIA_HOME` default to `.mafia` rather than using the ambiata prefix?
Obviously it'd need a migration of some sort.
@jystic

### CODE REVIEW

**Comment by domdere** [comment]
:+1: :+1:

**Comment by markhibberd** [comment]
@nhibberd How much will this break the CI caching?

**Comment by nhibberd** [comment]
It will reset all caches unless we set up some links etc

**Comment by markhibberd** [comment]
Can we hold off on this until we have time to deal with knock on consequences this will have a non-small impact on how infrastructure is currently configured.

**Comment by jacobstanley** [comment]
@tmcgilchrist I'm going to take over this PR

**Comment by jacobstanley** [comment]
Once this is merged we can switch the boris cache on and see if it works.

**Comment by jacobstanley** [comment]
The new cache location for GHC 8.0.1 on OS/X is:

```
$HOME/.mafia/packages/2/x86_64-apple-darwin/8.0.1
```

the sandbox will be stored in:

```
.cabal-sandbox/x86_64-apple-darwin/8.0.1
```

**Comment by erikd-ambiata** [comment]
:+1:

**Comment by thumphries** [comment]
👍  thanks for the target thing

**Pull request merged**
