### PR TITLE
Add mafia lock files for mafia itself

### PR DESCRIPTION
**Pull request by charleso**
! @nhibberd @jystic 

~~Just building the 7.8 lock file now~~
/jury approved @jystic

### CODE REVIEW

**Comment by charleso** [comment]
Updated. Please merge if the builds are green.

**Comment by charleso** [comment]
@jystic I think I've fixed the issue (for now), but obviously this is just another work around. Does it look ok for now?

**Comment by charleso** [comment]
Builds are green

**Comment by nhibberd** [comment]
bump @charleso

**Comment by jacobstanley** [comment]
👍

**Pull request merged**
