### PR TITLE
test: Use HTTPS instead of GIT protocol

### PR DESCRIPTION
**Pull request by erikd-ambiata**
Mainly so that people outside Ambiata can build/run the tests.

Signed-off-by: Erik de Castro Lopo <erik.decastrolopo@ambiata.com>

! @jystic

### CODE REVIEW

**Comment by markhibberd** [comment]
You don't need ambiata creds to use ssh, only an ssh key known to GitHub. So people can build and run tests outside as it is, admittedly https doesn't require any creds but makes it significantly more painful for people who have write access and use ssh so I am slightly skeptical. At some point submodules are always going to be easier for the people who use the same proptocol as the submodule by default and more difficult for everyone else. But it is still fairly straight forward to do by either adding a key to use ssh or by using git config to switch submodule protocol. Would a readme note explaining how to do it achieve the same thing, without making it harder for people who prefer ssh access?

**Comment by erikd-ambiata** [comment]
@markhibberd I agree with what you say in general, but in this specific case the changes I'm making are in the cli test scripts which do for instance:
```
git clone https://github.com/ambiata/p.git
```
Since this is only a test, that cloned repo is going to be used by the test and then deleted. That means its pretty much irrelevant whether it uses the Git or HTTPS protocol.

**Comment by markhibberd** [comment]
Yep, fair enough.

**Comment by jacobstanley** [comment]
👍 after rebase

**Comment by jacobstanley** [comment]
@erikd-ambiata I'm merging this ahead of my other changes

**Pull request merged**
