### PR TITLE
Fix annoyance where add-source dependencies are built twice

### PR DESCRIPTION
**Pull request by jacobstanley**
People might have noticed that sometimes on the build bot, source dependencies are being built twice.

This is because an older version of mafia has called 'cabal sandbox add-source' for each of the source dependencies and cabal thinks that it needs to build them, even though that have already been built.

You can fix this by just clearing the workspace on jenkins, but this fix provides a smoother upgrade and also prevents against problems with users calling add-source themselves.

/cc @charleso @nhibberd @markhibberd

### CODE REVIEW

**Comment by nhibberd** [comment]
Sounds legit :facepunch:

**Comment by thumphries** [comment]
if a user has manually done a `sandbox add-source`, it'd be pretty surprising to have it clobbered silently. could we print a warning message too?

**Comment by jacobstanley** [comment]
@thumphries yep i can do that

**Comment by jacobstanley** [comment]
/cc @thumphries it now prints out something like:

```
Removing add-source dependency: lib/disorder/disorder-aeson
Removing add-source dependency: lib/disorder/disorder-core
Removing add-source dependency: lib/disorder/disorder-corpus
Removing add-source dependency: lib/disorder/disorder-fsm
Removing add-source dependency: lib/disorder/disorder-lens
Removing add-source dependency: lib/p
Removing add-source dependency: lib/twine
Removing add-source dependency: lib/x/x-aeson
Removing add-source dependency: lib/x/x-attoparsec
Removing add-source dependency: lib/x/x-conduit
Removing add-source dependency: lib/x/x-either
Removing add-source dependency: lib/x/x-eithert
Removing add-source dependency: lib/x/x-exception
Removing add-source dependency: lib/x/x-htoml
Removing add-source dependency: lib/x/x-optparse
Removing add-source dependency: lib/x/x-templatehaskell
```

**Comment by thumphries** [comment]
sweet! thanks for that, was bound to get me eventually :shaved_ice:

**Pull request merged**
