### PR TITLE
Topic/split readme

### PR DESCRIPTION
**Pull request by erikd-ambiata**
First steps in making documentation better for external users. Changes to existing docs are minor, other than splitting them into separate linked documents.

! @jystic @tmcgilchrist 
/jury approved @jystic

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
What's the reason for splitting these up? Assuming there is another step to make the docs prettier or available as a github page (other doc serving site)/

**Comment by erikd-ambiata** [comment]
A couple of reasons. Firstly the main doc is getting a bit unweildy, mixing, building, using and command reference material. Secondly in its present form its difficult to add something like a Getting Started guide.

**Comment by jacobstanley** [comment]
I'm ok with the splitting, but I'm not sure what is new here and what is just splitting?

**Comment by erikd-ambiata** [comment]
The only thing that is new is the boostrapping document. Everything else is splitting with one minor tweak (adding "a light weight but" to "opinionated wrapper around Cabal").

**Comment by jacobstanley** [comment]
I would +1 without the bootstrapping doc, I think that should be a separate PR so people can comment

**Comment by erikd-ambiata** [comment]
WIll drop the bootstrapping doc.

**Comment by jacobstanley** [comment]
👍

**Pull request merged**
