### PR TITLE
Use simple-output for hoogle pkg list

### PR DESCRIPTION
**Pull request by charleso**
! @jystic 

https://github.com/ambiata/mafia/issues/165

Seems reasonable enough, unless simple-output was added too recently.
/jury approved @jystic

### CODE REVIEW

**Comment by nhibberd** [comment]
Got an example of the output?

**Comment by charleso** [comment]
Hmm, actually this is slightly wrong. Just want to check the build fails and will try something slightly different

**Comment by charleso** [comment]
> Got an example of the output?

```
> cabal exec -- ghc-pkg list --simple-output
Cabal-1.22.4.0 HUnit-1.5.0.0 MonadRandom-0.4.2.3 QuickCheck-2.8.2 SafeSemaphore-0.10.1 StateVar-1.1.0.4 ...
```

**Comment by charleso** [comment]
@jystic The build now passes. This ok by you? Is `cabal exec -- ghc-pkg list` going to the same has `sandbox hc-pkg list`?

**Comment by jacobstanley** [comment]
> @jystic The build now passes. This ok by you? Is `cabal exec -- ghc-pkg list` going to the same has `sandbox hc-pkg list`?

I think so, this seems to yield the right result for the package-dbs:
```
cabal exec -- sh -c 'echo "$GHC_PACKAGE_PATH"'
```

👍

**Comment by jystic** [comment]
👍

**Pull request merged**
