### PR TITLE
Use cabal_macros to provide Cabal version

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by novemberkilo** [comment]
This is what I see when I try to build this branch:

```
[navin:~/src/mafia] master 4s ± git checkout topic/Cabal-version 
Branch topic/Cabal-version set up to track remote branch topic/Cabal-version from origin.
Switched to a new branch 'topic/Cabal-version'
[navin:~/src/mafia] topic/Cabal-version ± ./mafia build
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Saved package config file is outdated:
• the Cabal version changed from Cabal-2.0.1.1 to Cabal-2.0.1.0
Re-run the 'configure' command.Process failed: cabal build -j --ghc-options=-Werror (exit code: 1)
```

So I did a `./mafia clean` and then `./mafia build` and got a clean build. However:

```
[navin:~/src/mafia] topic/Cabal-version 6s 141 ± ./dist/build/mafia/mafia --version
mafia: 0.0.1-20180514220348-7485b7a
built with cabal version: 2.0.1.1
[navin:~/src/mafia] topic/Cabal-version ± cabal --version                   
cabal-install version 2.0.0.0
compiled using version 2.0.1.0 of the Cabal library
```

Where is the `2.0.1.1` coming from? I'm confused.

**Comment by erikd** [comment]
The first build failure you see is to be expected because the `Setup.hs` has changed.

> I don't know where the 2.0.1.1 is coming from in the version.

That must be coming from the local sandbox and has nothing to do with what the `cabal-install` executable is build against. If you run `cabal list Cabal --installed` in the mafia build directory, then you will get `2.0.1.1`.

**Comment by novemberkilo** [comment]
@erikd I've been thinking about this and would like to add that personally, I am not in favour of overloading `--version` with this extra build information. They seem like separate things to me. I understand that for debugging purposes, you would like to have the version of the Cabal library that is used to build `mafia` -- may I suggest that this information be available under a `--build-info` or other flag and not be added to `--version`?

Anyway, that's just my $0.02 of course ... just contributing to the discussion.

**Comment by novemberkilo** [comment]
Yep, confirming that:

```
[navin:~/src/mafia] topic/Cabal-version ± cabal list Cabal --installed      
* Cabal
    Synopsis: A framework for packaging Haskell software
    Default available version: 2.2.0.1
    Installed versions: 2.0.1.0, 2.0.1.1
    Homepage: http://www.haskell.org/cabal/
    License:  BSD3
```

**Review by novemberkilo — APPROVED** [review]
Not really in a position to do much more than verify that things build etc. If the output is all per your expectations then please go ahead with this change.

**Review by novemberkilo — APPROVED** [review]

**Comment by novemberkilo** [comment]
I mustn't have write access so my approving this doesn't seem to be getting you any closer to merging it @erikd

**Comment by erikd** [comment]
@novemberkilo Fixed that! :)

**Pull request merged**
