### PR TITLE
Keep going when submodule sdist fails

### PR DESCRIPTION
**Pull request by thumphries**
Don't need to stop when sdist fails unless it breaks the solver

Some danger to this when depending on a fork, it could lead to you building against something off Hackage instead of a local submodule.

```
[tim@Tims-MacBook-Pro.local:~/src/aperture] % mafia depends
Failed to run 'cabal sdist' for source package: lib/bones
[tim@Tims-MacBook-Pro.local:~/src/aperture] % ../mafia/dist/build/Mafia/mafia depends
Failed to run 'cabal sdist' for source package: lib/bones
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ambiata-aperture-0.0.1 (user goal)
next goal: ambiata-bones (dependency of ambiata-aperture-0.0.1)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling --constraint ambiata-agriculture == 0.0.1 --constraint ambiata-bones-cloudwatch == 0.0.1 --constraint ambiata-bones-snooze == 0.0.1 --constraint ambiata-bones-test == 0.0.1 --constraint ambiata-charlotte == 0.0.1 --constraint ambiata-charlotte-test == 0.0.1 --constraint ambiata-clerk == 0.0.1 --constraint ambiata-disorder-aeson == 0.0.1 --constraint ambiata-disorder-core == 0.0.1 --constraint ambiata-disorder-corpus == 0.0.1 --constraint ambiata-disorder-fsm == 0.0.1 --constraint ambiata-disorder-lens == 0.0.1 --constraint ambiata-mismi-autoscaling == 0.0.1 --constraint ambiata-mismi-ec2-test == 0.0.1 --constraint ambiata-mismi-cloudwatch == 0.0.1 --constraint ambiata-mismi-cloudwatch-logs == 0.0.1 --constraint ambiata-mismi-cloudwatch-logs-test == 0.0.1 --constraint ambiata-mismi-cloudwatch-test == 0.0.1 --constraint ambiata-mismi-core == 0.0.1 --constraint ambiata-mismi-core-test == 0.0.1 --constraint ambiata-mismi-ec2 == 0.0.1 --constraint ambiata-mismi-ec2-test == 0.0.1 --constraint ambiata-mismi-elb == 0.0.1 --constraint ambiata-mismi-elb-test == 0.0.1 --constraint ambiata-mismi-emr == 0.0.1 --constraint ambiata-mismi-emr-test == 0.0.1 --constraint ambiata-mismi-iam == 0.0.1 --constraint ambiata-mismi-iam-test == 0.0.1 --constraint ambiata-mismi-rds == 0.0.1 --constraint ambiata-mismi-ec2-test == 0.0.1 --constraint ambiata-mismi-s3 == 0.0.1 --constraint ambiata-mismi-s3-test == 0.0.1 --constraint ambiata-mismi-sqs == 0.0.1 --constraint ambiata-mismi-sqs-test == 0.0.1 --constraint ambiata-mismi-sts == 0.0.1 --constraint ambiata-mismi-sts-test == 0.0.1 --constraint ambiata-p == 0.0.1 --constraint ambiata-p-test == 0.0.1 --constraint ambiata-passport == 0.0.1 --constraint ambiata-snooze == 0.0.1 --constraint ambiata-snooze-baton == 0.0.1 --constraint ambiata-snooze-test == 0.0.1 --constraint ambiata-twine == 0.0.1 --constraint ambiata-x-aeson == 0.0.1 --constraint ambiata-x-attoparsec == 0.0.1 --constraint ambiata-x-conduit == 0.0.1 --constraint ambiata-x-either == 0.0.1 --constraint ambiata-x-eithert == 0.0.1 --constraint ambiata-x-exception == 0.0.1 --constraint ambiata-x-htoml == 0.0.1 --constraint ambiata-x-optparse == 0.0.1 --constraint ambiata-x-templatehaskell == 0.0.1 (exit code: 1)
```

@jystic @markhibberd 
#114

### CODE REVIEW

**Comment by jacobstanley** [comment]
I wonder if we should have a submodule ignore file instead? It bothers me a little that this could happen without someone realising. Thoughts @markhibberd @thumphries ?

**Comment by thumphries** [comment]
Really not sure what is best here. An ignore file seems good.

Would also be nice to have `--force` or something to enable a more permissive build, a sledgehammer option in the style of `--allow-newer`.

**Comment by markhibberd** [comment]
I would be happy even with a flag, --ignore-sdist-failures, it is still an edge case and isn't going to happen that much. A blacklist also works, just not sure how much this is just for transitory/intetactive things where you wouldn't really need to keep list around

**Comment by jacobstanley** [comment]
+1 for `--ignore-sdist-failures`

**Comment by thumphries** [comment]
Closing and keeping the branch, I can reopen and implement the flag if anyone still wants this.

**Comment by jacobstanley** [comment]
maybe move it to `wip/badsdist` or `archive/badsdist` if that's ok?

**Comment by thumphries** [comment]
Moved to `archive/badsdist`.

**Pull request closed without merging**
