### PR TITLE
More module reorganisation

### PR DESCRIPTION
**Pull request by jacobstanley**
A little bit more reorg before I start to try and integrate my sandboxing upgrades

### CODE REVIEW

**Comment by jacobstanley** [comment]
There should be no logic changes here, just moving things around.

**Comment by jacobstanley** [comment]
@markhibberd do you think you can take a look at this? it should fairly straightforward just be moving things around.

**Comment by markhibberd** [comment]
:yen:

**Comment by charleso** [comment]
Nice :8ball:

**Pull request merged**
