### PR TITLE
Add -w flag to disable warnings during a build

### PR DESCRIPTION
**Pull request by jacobstanley**
/cc @tranma @thumphries 

Usage

```
$ mafia build -w
```

### CODE REVIEW

**Comment by tranma** [comment]
:+1:

**Comment by thumphries** [comment]
should this silence them entirely or just turn off `-Werror`?

**Comment by tranma** [comment]
I personally don't mind whether it's ghc -w or -Wwarn (since I'll do a normal build later)

**Comment by thumphries** [comment]
-Wwarn / -Wall is my preference. either way, I'm glad to replace my `sorry` alias 👍

**Comment by jacobstanley** [comment]
I matched it to the ghc `-w` argument i suppose, which silences them entirely

I'd be happy enough with either option, but I thought it might be weird to have a different meaning for `-w` between ghc and mafia.

**Comment by thumphries** [comment]
oh true, consistent with ghc is good 🎴

**Pull request merged**
