### PR TITLE
Use https for twine submodule

### PR DESCRIPTION
**Pull request by jacobstanley**
Without this mafia doesn't work on travis

### CODE REVIEW

**Comment by olorin** [comment]
:+1:

**Comment by nhibberd** [comment]
We generally use ssh for all our submodules, any reason these are https?

**Comment by jacobstanley** [comment]
@nhibberd it has to be so that mafia can be built without having github authorisation, this is the only special case i think

**Comment by nhibberd** [comment]
Ye touche nvm

**Pull request merged**
